### ISSUE TITLE
[Feature] Add community

### ISSUE THREAD

**Issue by semsemin** [Linkor-GDSC/Linkor-Android#11]
## TODO
- [x] add community screen
- [x] add comment screen
- [x] add post screen
