### ISSUE TITLE
[Feature] Add Korean Learning Screen

### ISSUE THREAD

**Issue by jhjalison01** [Linkor-GDSC/Linkor-Android#14]
## TODO
- [x] Add Korean Learning Screen UI
- [x] Make list of Korean Sentences
- [x] Connect with Google TTS API
