### ISSUE TITLE
[Feature] Add sign up settings

### ISSUE THREAD

**Issue by semsemin** [Linkor-GDSC/Linkor-Android#22]
## TODO
- [x] Add mode setting API
- [x] Add gender setting API
- [x] Add  communication method setting API
- [x] Add location setting API
- [x] Add time setting API
- [x] Add Introduction setting API
